---

- name: set timezone
  timezone:
    name: "{{ timezone_name }}"
  when: "{{ ansible_version.full|version_compare( '2.2', operator='ge', strict=False ) and update_timezone }}"
  tags: timezone_config

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items: "{{ init_apt_packages }}"

- name: update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: update_host_file
  tags: etc_hosts_config

- include: pip.yml
  when: pip_enabled
  tags: pip

- include: ntp.yml
  when: ntp_enabled
  tags: ntp
