---

- name: set timezone
  timezone:
    name: "{{ timezone_name }}"
  when: update_timezone
  tags: timezone_config

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ init_apt_packages }}"

- name: update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: update_host_file
  tags: etc_hosts_config

- include: python.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15.04', '<')
  tags: python

- include: pip.yml
  when: pip_enabled
  tags: pip

- include: ntp.yml
  when: ntp_enabled
  tags: ntp
