---

- name: ntp > config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - ntp.conf
  notify:
    - restart ntp
  tags: ntp_config

- name: ntp > service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - ntp
