---

- name: ntp > config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - ntp.conf
  notify:
    - restart ntp

- name: ntp > service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - ntp
